### ISSUE TITLE
No guns

### ISSUE THREAD

**Issue by elear** [elear/mtgvenue#23]
From Jordi:

I think we must not hold meetings in venues that allow people to carry firearms. I know this may be a conflict for many people that believe that self-defense is a right, but I agree that is true in the street, but inside a venue? If a venue is not considered safe so it “encourages people to carry a gun”, then there is no discussion on that, we should not meet in that venue.

**Comment by jordipalet** [comment]
I think this text could be included in Basic Venue Criteria

Even if the local laws allow participants to carry firearms, in order to be considered safe, the IETF Facilities must disallow them.

I will rate it as “Very Important” (I know we don’t have such category at the moment, but I will like to get this adopted as a replacement for “Mandatory” or an additional one), otherwise as “Important”

**Comment by eckelcu** [comment]
Some pushback against, not enough support for this one. Close as rejected by the WG.
Reference https://www.ietf.org/mail-archive/web/mtgvenue/current/msg01053.html
